### ISSUE TITLE
The UI does not show all installed plugins

### ISSUE THREAD

**Issue by dj0816** [avollkopf/craftbeerpi4-ui#18]
Hi Alexander, hi Manuel, I see your active development, many thanks! 
Unluckily, I can't get the plugins work on my environment. I updated to the lastest dev versions of all components (pulling directly from your github repos), still some of the plugins (e.g. the Buzzer-Plugin) are not available in the webbased user interface. 

Output from the command line: 
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/89589412/169043491-9c01b610-7d30-4a00-9461-407d8cefd6d2.png">
Buzzer module is installed on my system. 

Output in the Webbased UI: 
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/89589412/169043644-08a441e3-bf96-4f19-98a8-a9019ef0eeca.png">

Server Version: 4.0.6
Python: 3.9

Many thanks for your help already now! 
Best from Vienna, 
David

**Comment by dj0816** [comment]
Hi Alexander, I did a little digging and trying around. 
The issue was: I did not install the plugins as root; and pip3 installed clean without errors and did not require that access from me. 
When I installed the plugins again, as root with sudo, they were recognized by the cbpi4 system. 
Maybe you want to change that to less privileges required for plugin-installation - or update the documentation, that root / sudo is required. 
Continue the great work - best from Vienna, 
David

**Comment by avollkopf** [comment]
The documentation states that plugins have to be installed with sudo and I also have described that in every plugin README file. Problem is that I was not able to install the server itself w/o sudo. Therefore, all other plugins need to be installed in the same way.  At this point of time, I see no chance o change that.
