### ISSUE TITLE
Retain power setting on dashboard when at 0%

### ISSUE THREAD

**Issue by chappo** [avollkopf/craftbeerpi4-ui#20]
Hey Alexander,

Whats the best way of reporting graphical / display issues? 

First one would be to retain power setting on an actor when set to 0%? Currently it disappears and only shows the actor name and action drop-down. 

![image](https://user-images.githubusercontent.com/1019075/178249584-0edd8c7a-f3eb-41a3-8a07-fbb43ed9df96.png)

**Comment by avollkopf** [comment]
I need to look into it. It used to be in the past, but got changed when I implemented a pull request.

**Comment by avollkopf** [comment]
Fixed in development branch: https://github.com/avollkopf/craftbeerpi4-ui/commit/a4239ced56ae0694cf9ede758427def2c8bb34ac#diff-b03b2d66dd446a457d172d578d29a612928f1df3015036db4c5eec1b03fefc88
