### ISSUE TITLE
react-router-dom V6 upgrade requires changes

### ISSUE THREAD

**Issue by avollkopf** [avollkopf/craftbeerpi4-ui#24]
I am currently trying to upgrade the react components.

react scripts has been updated and is working.

react-router-dom upgrade from v5 to v6 will require changes in the routes (app.js), the private route (util/PrivateRoute.js) and useHistory() needs to be changed to useNavigate()

https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f

Prep work can be already done with the V5 version of react-router-dom:
https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f#get-started-upgrading-today

This may take some time. Experts are welcome to help :-)

**Comment by oekeur** [comment]
Will first need to get accustomed the code base, so maybe don't expect a result very soon.
Buuuut, definitely willing to contribute!

**Comment by avollkopf** [comment]
I was now able to move a bit forward. The [v6-router-test branch](https://github.com/avollkopf/craftbeerpi4-ui/tree/v6-router-test) is now based on the react v6 router. 

Main issue: Dashboard is not working --> Errors to be fixed
Other isues: Formatting different as V6 router does not allow container elements in the router -> Optimization required.

NOT A WORKING Branch yet

**Comment by avollkopf** [comment]
Adding a lint wih characters to dashboardcontext (https://github.com/avollkopf/craftbeerpi4-ui/blob/v6-router-test/cbpi4gui/src/components/dashboard/DashboardContext.js#L438) has the effect that the dashboard is shown.

--> Style issue with the rendered containers / div and not a general dashboard issue

![grafik](https://user-images.githubusercontent.com/43980694/210617263-ff7e4f3b-eb22-4c20-8acc-49da3649913e.png)

**Comment by avollkopf** [comment]
Seems to work w/o issues -> merged into development branch. Next step: migrate to material ui V5
