### ISSUE TITLE
Kettle on Auto Mode: Displayed Value for Actor is always ON

### ISSUE THREAD

**Issue by Admiraldr** [avollkopf/craftbeerpi4-ui#33]
I am running a Kettle on Auto Run.

The Lamps for the Actor (seperate Actor Lamp and the Field in the Kettle control) are always ON, even if the PID turns off the GPIO. 

In the image the PV (Ist) is higher than SP (Soll), the GPIOs real state is OFF (proven by a hardware lamp):
![image](https://user-images.githubusercontent.com/31703558/213488414-f122ae1b-9c73-4966-b4a6-52ac35294f06.png)

**Comment by avollkopf** [comment]
Not an issue and it has been discussed more than a year ago. The PID logic switches the actor on and regulates only the power. 

-> Actor itself is on, but power might be at 0% -> LED status is on.
